#端口号
server:
  port: 11001
 
#应用名称 
spring:
  application:
    name: eureka-server
    
  #数据源
  datasource:
    username: root
    password: CAOGANG.0858
    url: jdbc:mysql://localhost:3306/demo001?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver    
  
#mybatis配置
mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.caogang.entity
  
#展示SQL语句
logging:
  level:
    com:
      caogang:
        mapper : debug


#配置分页插件参数
pagehelper:
  helper-dialect: mysql
  params: count=countSql 
  reasonable: true
  support-methods-arguments: true
 
#注册中心地址   
eureka:
  instance:
    instance-id:  eureka-server1
    appname:  ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
      
    
      


 
 

